---
apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: authentication
spec:
  auth_service: "oidc-auth:8080"
  allowed_request_headers:
    - "Cookie"
    - "Authorization"
  allowed_authorization_headers:
    - "Authorization"
    - "Set-cookie"

---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: oidc-auth
spec:
  prefix: /callbac
  service: oidc-auth:8080
  rewrite: ""  # disable rewrite  https://www.getambassador.io/docs/latest/topics/using/rewrites/

---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: dex
spec:
  prefix: /dex/
  service: dex:5556
  rewrite: ""
  bypass_auth: true


