---
apiVersion: getambassador.io/v2
kind: AuthService
metadata:
  name: authentication
spec:
  auth_service: "oidc-auth:8080"
  allowed_request_headers:
    - "Authorization"
    - "Cookie"
  allowed_authorization_headers:
    - "Authorization"
    - "Set-cookie"

---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: oidc-auth
spec:
  prefix: /callback
  service: oidc-auth:8080

---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: dex
spec:
  prefix: /dex
  service: dex:5556


