apiVersion: v1
kind: Service
metadata:
  name: oidc-auth
spec:
  type: ClusterIP
  selector:
    app: oidc-auth
  ports:
    - port: 8080
      targetPort: http-api
---
apiVersion: v1
kind: Service
metadata:
  name: oidc-auth-nodeport
spec:
  type: NodePort
  selector:
    app: oidc-auth
  ports:
    - port: 8080
      targetPort: http-api
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oidc-auth
  template:
    metadata:
      labels:
        app: oidc-auth
    spec:
      # kubectl create secret docker-registry regcred --docker-server=docker.pkg.github.com ....
      imagePullSecrets:
        - name: regcred
      containers:
        - name: oidc-auth
          image: docker.pkg.github.com/fezho/oidc-auth-service/auth-service:7a1a07bb33e01c72794d5f73c8da204b0ff57cc2-dirty
          command: ["/usr/local/bin/auth-service", "--config", "/etc/oidc-auth/cfg/config.yaml"]
          ports:
            - name: http-api
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/oidc-auth/cfg
            - name: db
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: oidc-auth
        - name: db
          persistentVolumeClaim:
            claimName: auth-pvc

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: oidc-auth
data:
  config.yaml: |-
    web:
      http: 0.0.0.0:8080
    storage:
      type: bolt
      config:
        path: "/data/data.bin"
        bucketName: "session"
        maxAge: 1800
    oidc:
      dexAddress: http://dex:5556
      issuer: http://192.168.99.123:30036/dex
      redirectURL: http://192.168.99.123:30036/auth/callback
      clientID: auth-service
      clientSecret: "ZXhhbXBsZS1hcHAtc2VjcmV0"
      scopes:
        - email
        - profile
      usernameClaim: email
    logger:
      level: "debug"
      format: "json"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv0002"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


