---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8088
      targetPort: 8080
      nodePort: 30036  # Optional: Define the port you would like exposed
      protocol: TCP
  selector:
    service: ambassador
